### ISSUE TITLE
tracker 协议讨论

### ISSUE THREAD

**Issue by PlexPt** [PlexPt/rocket-pt#6]
tracker可以有很多种协议，如
1. http/https
2. UDP
3. ws

np的tracker是基于http的，这会有性能瓶颈，这里讨论一下其他协议的可行性

**Comment by CBEpt** [comment]
希望可以同时支持ipv4和v6，这样校园网用户就能在纯v6下免流量费下载了（正常向tracker汇报
另外猫站的这个帖子也值得一看：
/forums.php?action=viewtopic&forumid=25&topicid=8181

**Comment by Rhilip** [comment]
从nphp的实现来看，基于http的完全没有性能瓶颈。udp会有丢包风险，这对pt来说是不可接受的。ws没试过，但考虑要建立长连接，我认为对服务器性能是个挑战。
从#7 的角度来说，如果作者想尽快做个demo出来，那http是最好实现的（前有nphp，后有unit3d做参考）

---

另外，我觉得就tracker协议来说，应该只的是实现哪些bep特性。而不是指protocol。

**Comment by PlexPt** [comment]
按照bep15实现了一个

**Comment by LWWD** [comment]
使用netty  http就行了。 UDP不适合做这种场景，WS多用户对服务器性能要求较高

**Comment by PlexPt** [comment]
暂定http
